#!/usr/bin/env python2

import pandas as pd
import Quandl
import stopit

import modules.config_details as conf_info
import modules.tickers_helpers as helpers

def process_tickers(list, function):
  for ticker in list:
    function(ticker, timeout=10)

@stopit.threading_timeoutable(default='not finished')
def outstanding_shares(ticker):
  current_request = conf_info.quandl_out_shares_db_id + '/' + ticker.upper().strip() + '_TOTAL_COMMON_SHARES_OUTSTANDING_Q'
  outstanding_shares_filename = conf_info.fundamentals_dir + conf_info.get_quandle_outstanding_shares_filename(ticker)
    
  try:
    print 'Processing ticker ' + ticker
    current_dataframe = Quandl.get(current_request)
    # the DataFrame seems already sorted by Date
    current_dataframe.to_csv(outstanding_shares_filename)
  except Exception, e:
    print '~~~ Failed ticker: ' + ticker + ' ~~~', str(e)

process_tickers(helpers.get_all_tickers_lists_csv_files(),outstanding_shares)
