#!/usr/bin/env python3

import pandas as pd
import pandas.io.data as web
import datetime as dt
import matplotlib.pyplot as plt

# prendi da yahoo (Saipem, borsa Milano)
smp_mi = web.DataReader('SPM.MI','yahoo',dt.date(2016,1,1), dt.date(2016,1,20))

# salva il csv
smp_mi.to_csv('smp_mi.csv')

# carica il csv
smp_mi_loaded = pd.read_csv('smp_mi.csv')


# printa il csv
smp_mi_loaded['Close'].plot()
plt.show()

print(smp_mi_loaded['Close'])



