#!/usr/bin/env python3

import datetime as dt

# https://docs.python.org/3/library/datetime.html#module-datetime

now = dt.date.today()
print(now)

one_day_ago = now + dt.timedelta(days=-1)
print(one_day_ago)
